TRAIN_DATA = [
    ("journal", {"entities": [(0, 7, "JOURNAL")]}),
    ###
    ("log account", {"entities": [(0, 3, "LOGIN"), (4, 11, "ACCOUNT")]}),
    ("login", {"entities": [(0, 5, "LOGIN")]}),
    ###
    ("open", {"entities": [(0, 4, "OPEN")]}),
    ("access", {"entities": [(0, 6, "OPEN")]}),
    ("show", {"entities": [(0, 4, "OPEN")]}),
    ("view", {"entities": [(0, 4, "OPEN")]}),
    ###
    ("buy", {"entities": [(0, 3, "TRADE_ACTION")]}),
    ("bought", {"entities": [(0, 6, "TRADE_ACTION")]}),
    ("purchased", {"entities": [(0, 9, "TRADE_ACTION")]}),
    ("acquired", {"entities": [(0, 8, "TRADE_ACTION")]}),
    ("purchase", {"entities": [(0, 8, "TRADE_ACTION")]}),
    ("acquire", {"entities": [(0, 7, "TRADE_ACTION")]}),
    ("add", {"entities": [(0, 3, "TRADE_ACTION")]}),
    ("get", {"entities": [(0, 3, "TRADE_ACTION")]}),
    ("initiated", {"entities": [(0, 9, "TRADE_ACTION")]}),
    ("started", {"entities": [(0, 7, "TRADE_ACTION")]}),
    ("placed", {"entities": [(0, 6, "TRADE_ACTION")]}),
    ###
    ("btc", {"entities": [(0, 3, "ASSET_NAME")]}),
    ("ethereum price today", {"entities": [(0, 8, "ASSET_NAME")]}),
    ("eth market cap", {"entities": [(0, 3, "ASSET_NAME")]}),
    ("bitcoin historical data", {"entities": [(0, 7, "ASSET_NAME")]}),
    ("btc all-time high", {"entities": [(0, 3, "ASSET_NAME")]}),
    ("ada to usd conversion", {"entities": [(0, 3, "ASSET_NAME")]}),
    ("cardano staking rewards", {"entities": [(0, 7, "ASSET_NAME")]}),
    ("xrp current value", {"entities": [(0, 3, "ASSET_NAME")]}),
    ("ripple news update", {"entities": [(0, 6, "ASSET_NAME")]}),
    ("matic network", {"entities": [(0, 5, "ASSET_NAME")]}),
    ("polygon gas fees", {"entities": [(0, 7, "ASSET_NAME")]}),
]
